package crs.login.ui;

import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    private UserManager userManager = new UserManager();
    private LoginHistoryManager historyManager = new LoginHistoryManager();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogIn = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        comboBoxRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        labelForgetPassword = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogIn.setBackground(new java.awt.Color(51, 51, 51));
        panelLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelLogIn.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 790, -1));
        panelLogIn.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 470));
        panelLogIn.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 470));
        panelLogIn.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 790, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("CRS System");
        panelLogIn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        panelLogIn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        panelLogIn.add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 280, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role:");
        panelLogIn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));
        panelLogIn.add(txtFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 280, -1));

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACADEMIC_OFFICER", "COURSE_ADMIN" }));
        panelLogIn.add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 280, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        panelLogIn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelLogIn.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        btnLogIn.setText("Login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        panelLogIn.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        labelForgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelForgetPassword.setText("Forgot Password?");
        labelForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelForgetPasswordMouseClicked(evt);
            }
        });
        panelLogIn.add(labelForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));
        panelLogIn.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 790, -1));

        getContentPane().add(panelLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        String email = txtFieldEmail.getText().trim().toLowerCase();
        String password = txtFieldPassword.getText();
        String role = comboBoxRole.getSelectedItem().toString();

        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter email and password.",
                    "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        User user = userManager.authenticate(email, password, role);

        if (user == null) {
            JOptionPane.showMessageDialog(this,
                    "Invalid email / password / role.",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!user.isActive()) {
            JOptionPane.showMessageDialog(this,
                    "Your account is deactivated. Please contact admin.",
                    "Login Failed",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ login history me entry
        historyManager.logLogin(user.getId());

        // ✅ role ke mutabiq dashboard open
        switch (user.getRole().toUpperCase()) {
            case "ACADEMIC_OFFICER":
                new AcademicOfficerDashboard(user).setVisible(true);
                break;

            case "COURSE_ADMIN":
                new CourseAdminDashboard(user).setVisible(true);
                break;

            default:
                JOptionPane.showMessageDialog(this,
                        "Unknown role: " + user.getRole(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }

        this.dispose(); // login window close
    }//GEN-LAST:event_btnLogInActionPerformed

    private void labelForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgetPasswordMouseClicked
        new ForgetPassword().setVisible(true);
        this.dispose();  // close Login window
    }//GEN-LAST:event_labelForgetPasswordMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelForgetPassword;
    private javax.swing.JPanel panelLogIn;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldPassword;
    // End of variables declaration//GEN-END:variables
}
