package crs.login;

import com.sun.jdi.connect.LaunchingConnector;
import crs.eligibility.EligibilityCheckUI;
import crs.eligibility.EligibilityService;
import crs.reporting.CourseRepository;
import crs.reporting.GradesRepository;
import crs.reporting.ReportService;
import crs.reporting.StudentRepository;
import crs.reporting.ReportFormGUI;
import crs.util.ResourceUtil;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public abstract class BaseDashboard extends javax.swing.JFrame {

    private final User currentUser;
    private final LoginHistoryManager historyManager = new LoginHistoryManager();

    protected StudentRepository sRepo;
    protected CourseRepository cRepo;
    protected GradesRepository gRepo;

    // Shared UI component
    protected JPanel mainPanel;
    protected JLabel lblTitle;
    protected JButton btnManageUsers;
    protected JButton btnUserLoginHistory;
    protected JButton btnEligibilityCheck;
    protected JButton btnAcademicReport;
    protected JButton btnLogout;

    // Placeholder panel where child dashboards can add extra buttons
    protected JPanel roleSpecificPanel;

    /**
     * Creates new form BaseDashboard
     */
    public BaseDashboard(User user, String titleText) {
        //initComponents();
        this.currentUser = user;

        // Load repositories
        sRepo = new StudentRepository();
        sRepo.loadStudents(ResourceUtil.get("student_information.csv"));

        cRepo = new CourseRepository();
        cRepo.loadCourses(ResourceUtil.get("course_assessment_information.csv"));

        gRepo = new GradesRepository();
        gRepo.loadGrades(ResourceUtil.get("grades.csv"));
        
        initCommonUI(titleText);      
        initRoleSpecificUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Build common UI for both Academic Officer and Course Admin
     */
    private void initCommonUI(String titleText) {
        setTitle("CRS System - Dashboard");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // MAIN PANEL
        mainPanel = new JPanel();
        mainPanel.setBackground(new Color(40, 40, 40));
        mainPanel.setLayout(null);

        // TITLE
        lblTitle = new JLabel(titleText, SwingConstants.CENTER);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setBounds(200, 20, 500, 40);
        mainPanel.add(lblTitle);

        // COMMON BUTTONS
        btnManageUsers = createButton("Manage Users", 150);
        btnManageUsers.addActionListener(e -> {
            new ManageUsers(currentUser).setVisible(true);
            dispose();
        });

        btnUserLoginHistory = createButton("User Login History", 220);
        btnUserLoginHistory.addActionListener(e -> {
            new UserLoginHistory(currentUser).setVisible(true);
            dispose();
        });

        btnEligibilityCheck = createButton("Eligibility Check", 290);
        // Add task 3 screen here:
        btnEligibilityCheck.addActionListener(e -> {
            new EligibilityCheckUI(currentUser, new EligibilityService(sRepo, cRepo, gRepo)).setVisible(true);
            dispose();
        });

        btnAcademicReport = createButton("Academic Performance Report", 360);
        btnAcademicReport.addActionListener(e -> {
            launchReportForm();
        });
        // btnAcademicReport.addActionListener(...)

        mainPanel.add(btnManageUsers);
        mainPanel.add(btnUserLoginHistory);
        mainPanel.add(btnEligibilityCheck);
        mainPanel.add(btnAcademicReport);

        // LOGOUT
        btnLogout = new JButton("Logout");
        btnLogout.setBounds(380, 500, 150, 40);
        btnLogout.addActionListener(e -> {
            new Main().setVisible(true);
            dispose();
        });
        mainPanel.add(btnLogout);

        // ROLE-SPECIFIC PANEL (child dashboards will place extra buttons here)
        roleSpecificPanel = new JPanel();
        roleSpecificPanel.setBackground(new Color(40, 40, 40));
        roleSpecificPanel.setLayout(null);
        roleSpecificPanel.setBounds(0, 430, 900, 70);

        mainPanel.add(roleSpecificPanel);

        // Add main panel
        add(mainPanel);
    }

    protected JButton createButton(String text, int y) {
        JButton btn = new JButton(text);
        btn.setBounds(330, y, 240, 45);
        return btn;
    }

    protected void launchReportForm() {
        ReportService rs = new ReportService(sRepo, cRepo, gRepo);
        new ReportFormGUI(rs, this).setVisible(true);
        dispose();
    }

    protected abstract void initRoleSpecificUI();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
