package crs.login;

import javax.swing.JOptionPane;

public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForgetPassword = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelForgetPassword = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        txtFieldEmail = new javax.swing.JTextField();
        labelRole = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        comboBoxRole = new javax.swing.JComboBox<>();
        labelPassword = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnForget = new javax.swing.JButton();
        txtFieldNewPassword = new javax.swing.JTextField();
        labelNewPassword = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelForgetPassword.setBackground(new java.awt.Color(51, 51, 51));
        panelForgetPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelForgetPassword.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 780, -1));
        panelForgetPassword.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 470));
        panelForgetPassword.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 470));
        panelForgetPassword.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 780, -1));

        labelForgetPassword.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelForgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelForgetPassword.setText("Forget Password");
        panelForgetPassword.add(labelForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Email:");
        panelForgetPassword.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        panelForgetPassword.add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 280, -1));

        labelRole.setForeground(new java.awt.Color(255, 255, 255));
        labelRole.setText("Role:");
        panelForgetPassword.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));
        panelForgetPassword.add(txtFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 280, -1));

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "COURSE_ADMIN", "LECTURER", "STUDENT" }));
        panelForgetPassword.add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 280, -1));

        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password:");
        panelForgetPassword.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, 10));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelForgetPassword.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        btnForget.setText("Submit");
        btnForget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgetActionPerformed(evt);
            }
        });
        panelForgetPassword.add(btnForget, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));
        panelForgetPassword.add(txtFieldNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 280, -1));

        labelNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelNewPassword.setText("New Password:");
        panelForgetPassword.add(labelNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        panelForgetPassword.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 780, -1));

        getContentPane().add(panelForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgetActionPerformed
        String email = txtFieldEmail.getText().trim();
    String oldPassword = txtFieldPassword.getText().trim();
    String newPassword = txtFieldNewPassword.getText().trim();
    String role = comboBoxRole.getSelectedItem().toString();

    if (email.isEmpty() || oldPassword.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserManager um = new UserManager();
    boolean success = um.resetPassword(email, oldPassword, role, newPassword);

    if (success) {
        JOptionPane.showMessageDialog(this,
                "Password updated successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);

        new Main().setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(this,
                "Invalid email, old password, or role.",
                "Failed", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnForgetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    new Main().setVisible(true);
    this.dispose();  // close Login window
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnForget;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelForgetPassword;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRole;
    private javax.swing.JPanel panelForgetPassword;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldNewPassword;
    private javax.swing.JTextField txtFieldPassword;
    // End of variables declaration//GEN-END:variables
}
