package crs.login;

import crs.email.EmailService;
import crs.email.EmailTemplates;
import jakarta.mail.MessagingException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageUsers extends javax.swing.JFrame {

    private final User currentUser;
    UserManager userManager = new UserManager();

    private void loadTable() {
        List<User> users = userManager.loadAllUsers();
        String[] cols = {"ID", "Name", "Email", "Username", "Role", "Status"};

        DefaultTableModel model = new DefaultTableModel(cols, 0);

        for (User u : users) {
            model.addRow(new Object[]{
                u.getId(), u.getName(), u.getEmail(),
                u.getUsername(), u.getRole(), u.getStatus()
            });
        }

        tableManageUsers.setModel(model);
    }

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers(User user) {
        initComponents();
        loadTable();
        this.currentUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManageUsers = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblManageUsers = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableManageUsers = new javax.swing.JTable();
        txtFieldFullName = new javax.swing.JTextField();
        labelFullName = new javax.swing.JLabel();
        txtFieldEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtFieldUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        comboBoxRole = new javax.swing.JComboBox<>();
        labelRole = new javax.swing.JLabel();
        comboBoxStatus = new javax.swing.JComboBox<>();
        labelStatus = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelManageUsers.setBackground(new java.awt.Color(51, 51, 51));
        panelManageUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelManageUsers.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, -1));
        panelManageUsers.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 580));
        panelManageUsers.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, 580));
        panelManageUsers.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 830, -1));

        lblManageUsers.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblManageUsers.setText("Manage Users");
        panelManageUsers.add(lblManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panelManageUsers.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 110, -1));

        tableManageUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableManageUsers);

        panelManageUsers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 460));
        panelManageUsers.add(txtFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 240, -1));

        labelFullName.setForeground(new java.awt.Color(255, 255, 255));
        labelFullName.setText("Full Name:");
        panelManageUsers.add(labelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));
        panelManageUsers.add(txtFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 240, -1));

        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Email:");
        panelManageUsers.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
        panelManageUsers.add(txtFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 240, -1));

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Username:");
        panelManageUsers.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));
        panelManageUsers.add(txtFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 240, -1));

        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("Password:");
        panelManageUsers.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACADEMIC_OFFICER", "COURSE_ADMIN" }));
        panelManageUsers.add(comboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 240, -1));

        labelRole.setForeground(new java.awt.Color(255, 255, 255));
        labelRole.setText("Role:");
        panelManageUsers.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        comboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        panelManageUsers.add(comboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 240, -1));

        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Status:");
        panelManageUsers.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelManageUsers.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 110, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        panelManageUsers.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 110, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panelManageUsers.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 110, -1));
        panelManageUsers.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 830, -1));

        getContentPane().add(panelManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String id = "U" + System.currentTimeMillis();
        String name = txtFieldFullName.getText();
        String email = txtFieldEmail.getText().toLowerCase();
        String username = txtFieldUserName.getText();
        String password = txtFieldPassword.getText();
        String role = comboBoxRole.getSelectedItem().toString();
        String status = comboBoxStatus.getSelectedItem().toString();

        User newUser = userManager.createUserObj(id, name, email, username, password, role, status);

        userManager.addUser(newUser);
        loadTable();
        JOptionPane.showMessageDialog(this, "User added!");

        new EmailService().sendEmail(email, "CRS Account Created", EmailTemplates.accountCreated(name, role));
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tableManageUsers.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first!");
            return;
        }

        String id = tableManageUsers.getValueAt(row, 0).toString();
        String name = txtFieldFullName.getText();
        String email = txtFieldEmail.getText();
        String username = txtFieldUserName.getText();
        String password = txtFieldPassword.getText();
        String role = comboBoxRole.getSelectedItem().toString();
        String status = comboBoxStatus.getSelectedItem().toString();

        User updated = userManager.createUserObj(id, name, email, username, password, role, status);

        userManager.updateUser(updated);
        loadTable();

        JOptionPane.showMessageDialog(this, "User updated!");

        new EmailService().sendEmail(email, "CRS Account Edited", EmailTemplates.accountEdited(name));
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tableManageUsers.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a user!");
            return;
        }

        String userId = tableManageUsers.getValueAt(row, 0).toString();
        String name = tableManageUsers.getValueAt(row, 1).toString();
        String email = tableManageUsers.getValueAt(row, 2).toString();

        userManager.deleteUser(userId);
        loadTable();

        JOptionPane.showMessageDialog(this, "User deleted.");

        new EmailService().sendEmail(email, "CRS Account Deleted", EmailTemplates.accountDeleted(name));
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (currentUser.getRole().equalsIgnoreCase("course_admin")){
            new CourseAdminDashboard(currentUser).setVisible(true);
        }
        else{
            new AcademicOfficerDashboard(currentUser).setVisible(true);
        }        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> comboBoxRole;
    private javax.swing.JComboBox<String> comboBoxStatus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFullName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel lblManageUsers;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel panelManageUsers;
    private javax.swing.JTable tableManageUsers;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldFullName;
    private javax.swing.JTextField txtFieldPassword;
    private javax.swing.JTextField txtFieldUserName;
    // End of variables declaration//GEN-END:variables
}
