package crs.reporting.ui;

import crs.reporting.CourseRepository;
import crs.reporting.GradesRepository;
import crs.reporting.ReportService;
import crs.reporting.StudentRepository;
import crs.reporting.email.EmailService;
import crs.reporting.models.StudentReport;
import crs.reporting.pdf.PdfExporter;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashi
 */
public class ReportFormGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportFormGUI.class.getName());
    private static ReportService reportService;
    private static String pdfFileName;

    /**
     * Creates new form ReportFormGUI
     */
    public ReportFormGUI(ReportService rs) {
        initComponents();
        this.reportService = rs;
        btnGenerate.setEnabled(false);
        btnExportPDF.setEnabled(false);
        btnSendEmail.setEnabled(false);
        addStudentIdListener();

        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                applyStudentIdMask(e);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMajor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrades = new javax.swing.JTable();
        btnSendEmail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelStudentId.setText("Student Id:");

        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        btnExportPDF.setText("Export PDF");
        btnExportPDF.addActionListener(this::btnExportPDFActionPerformed);

        jLabel1.setText("Name");

        jLabel2.setText("Major");

        jLabel3.setText("Year");

        txtName.setEditable(false);

        txtMajor.setEditable(false);

        txtYear.setEditable(false);

        tableGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Credits", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tableGrades);

        btnSendEmail.setText("Send Email");
        btnSendEmail.addActionListener(this::btnSendEmailActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(txtMajor)
                                .addComponent(txtYear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExportPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(btnSendEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerate)
                    .addComponent(btnExportPDF))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSendEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String studentId = txtStudentId.getText().trim();

        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID.");
            return;
        }

        StudentReport report = reportService.generateReport(studentId);

        if (report == null) {
            JOptionPane.showMessageDialog(this, "Student ID not found.");
            clearFields();
            return;
        }

        // Fill student info fields
        txtName.setText(report.getStudentName());
        txtMajor.setText(report.getMajor());
        txtYear.setText(report.getYear());

        // Fill table
        DefaultTableModel model = (DefaultTableModel) tableGrades.getModel();
        model.setRowCount(0); // clear old data

        report.getEntries().forEach(c -> {
            model.addRow(new Object[]{
                c.getCourseName(),
                c.getCredits(),
                c.getGrade()
            });
        });
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        String studentId = txtStudentId.getText().trim();

        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID first.");
            return;
        }

        StudentReport report = reportService.generateReport(studentId);

        if (report == null) {
            JOptionPane.showMessageDialog(this, "Please generate a valid report first.");
            return;
        }

        // Export Report
        pdfFileName = studentId + "_Report.pdf";
        PdfExporter exporter = new PdfExporter();
        exporter.exportReport(report, pdfFileName);

        // Enable send email button
        btnSendEmail.setEnabled(true);

        // OPEN THE PDF AUTOMATICALLY
        try {
            File pdf = new File(pdfFileName);
            if (pdf.exists()) {
                Desktop.getDesktop().open(pdf);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        String studentId = txtStudentId.getText().trim();
        String email = reportService.getStudentEmail(studentId);

        if (email == null) {
            JOptionPane.showMessageDialog(this, "Student email not found.");
            return;
        }

        // Email sender credentials
        EmailService emailService = new EmailService(
                "javagroup23@gmail.com",
                "ILoveJava"
        );

        boolean sent = emailService.sendEmail(
                email,
                "Academic Performance Report",
                "Dear student,\n\nPlease find attached your academic report.\n\nRegards,\nCRS System",
                pdfFileName
        );

        if (sent) {
            JOptionPane.showMessageDialog(this, "Email sent successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to send email.");
        }
    }//GEN-LAST:event_btnSendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        StudentRepository studentRepo = new StudentRepository();
        studentRepo.loadStudents(getResourcePath("student_information.csv"));

        CourseRepository courseRepo = new CourseRepository();
        courseRepo.loadCourses(getResourcePath("course_assessment_information.csv"));

        GradesRepository gradeRepo = new GradesRepository();
        gradeRepo.loadGrades(getResourcePath("grades.csv"));

        reportService = new ReportService(studentRepo, courseRepo, gradeRepo);
        new ReportFormGUI(reportService).setVisible(true);
    }

    private void clearFields() {
        txtName.setText("");
        txtMajor.setText("");
        txtYear.setText("");

        DefaultTableModel model = (DefaultTableModel) tableGrades.getModel();
        model.setRowCount(0);
    }

    private void addStudentIdListener() {
        txtStudentId.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            private void updateState() {
                String text = txtStudentId.getText().trim();
                boolean isValid = isValidStudentId(text);

                btnGenerate.setEnabled(isValid);
                btnExportPDF.setEnabled(isValid);
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }
        });
    }

    private boolean isValidStudentId(String id) {
        return id.matches("S\\d{3}");
    }

    private void applyStudentIdMask(java.awt.event.KeyEvent e) {
        String text = txtStudentId.getText();

        // Character the user typed
        char ch = e.getKeyChar();

        // Only allow backspace/delete always
        if (ch == '\b' || ch == 127) {
            return;
        }

        // Length check (max 4 chars)
        if (text.length() >= 4) {
            e.consume();
            return;
        }

        // First character must be 'S'
        if (text.length() == 0) {
            // auto convert to uppercase S
            if (ch == 's' || ch == 'S') {
                txtStudentId.setText("S");
            } else {
                e.consume();
            }
            e.consume();
            return;
        }

        // Remaining characters must be digits
        if (!Character.isDigit(ch)) {
            e.consume();
        }
    }

    private static String getResourcePath(String fileName) {
        try {
            return new File(
                    ReportFormGUI.class.getClassLoader().getResource(fileName).toURI()
            ).getAbsolutePath();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStudentId;
    private javax.swing.JTable tableGrades;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
