package crs.reporting;

import crs.reporting.CourseRepository;
import crs.reporting.GradesRepository;
import crs.reporting.ReportService;
import crs.reporting.StudentRepository;
import crs.reporting.StudentReport;
import crs.reporting.PdfExporter;
import crs.util.ResourceUtil;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashi
 */
public class ReportFormGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportFormGUI.class.getName());
    private static ReportService reportService;
    private static String pdfFileName;
    private javax.swing.JFrame parentWindow;

    /**
     * Creates new form ReportFormGUI
     */
    public ReportFormGUI(ReportService rs, javax.swing.JFrame parent) {
        initComponents();
        this.reportService = rs;
        this.parentWindow = parent;
        
        btnGenerate.setEnabled(false);
        btnExportPDF.setEnabled(false);
        addStudentIdListener();

        txtStudentId.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                applyStudentIdMask(e);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMajor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrades = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        labelStudentId.setText("Student Id:");

        btnGenerate.setText("Generate Report");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        btnExportPDF.setText("Export PDF");
        btnExportPDF.addActionListener(this::btnExportPDFActionPerformed);

        jLabel1.setText("Name");

        jLabel2.setText("Major");

        jLabel3.setText("Year");

        txtName.setEditable(false);

        txtMajor.setEditable(false);

        txtYear.setEditable(false);

        tableGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Name", "Credits", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tableGrades);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtMajor)
                                    .addComponent(txtYear)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnExportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerate)
                    .addComponent(btnExportPDF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String studentId = txtStudentId.getText().trim();

        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID.");
            return;
        }

        StudentReport report = reportService.generateReport(studentId);

        if (report == null) {
            JOptionPane.showMessageDialog(this, "Student ID not found.");
            clearFields();
            return;
        }

        // Fill student info fields
        txtName.setText(report.getStudentName());
        txtMajor.setText(report.getMajor());
        txtYear.setText(report.getYear());

        // Fill table
        DefaultTableModel model = (DefaultTableModel) tableGrades.getModel();
        model.setRowCount(0); // clear old data

        report.getEntries().forEach(c -> {
            model.addRow(new Object[]{
                c.getCourseName(),
                c.getCredits(),
                c.getGrade()
            });
        });
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        String studentId = txtStudentId.getText().trim();

        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID first.");
            return;
        }

        StudentReport report = reportService.generateReport(studentId);

        if (report == null) {
            JOptionPane.showMessageDialog(this, "Please generate a valid report first.");
            return;
        }

        // Export Report
        pdfFileName = studentId + "_Report.pdf";
        PdfExporter exporter = new PdfExporter();
        exporter.exportReport(report, pdfFileName);

        // OPEN THE PDF AUTOMATICALLY
        try {
            File pdf = new File(pdfFileName);
            if (pdf.exists()) {
                Desktop.getDesktop().open(pdf);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExportPDFActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (parentWindow != null){
            parentWindow.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void clearFields() {
        txtName.setText("");
        txtMajor.setText("");
        txtYear.setText("");

        DefaultTableModel model = (DefaultTableModel) tableGrades.getModel();
        model.setRowCount(0);
    }

    private void addStudentIdListener() {
        txtStudentId.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            private void updateState() {
                String text = txtStudentId.getText().trim();
                boolean isValid = isValidStudentId(text);

                btnGenerate.setEnabled(isValid);
                btnExportPDF.setEnabled(isValid);
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateState();
            }
        });
    }

    private boolean isValidStudentId(String id) {
        return id.matches("S\\d{3}");
    }

    private void applyStudentIdMask(java.awt.event.KeyEvent e) {
        String text = txtStudentId.getText();

        // Character the user typed
        char ch = e.getKeyChar();

        // Only allow backspace/delete always
        if (ch == '\b' || ch == 127) {
            return;
        }

        // Length check (max 4 chars)
        if (text.length() >= 4) {
            e.consume();
            return;
        }

        // First character must be 'S'
        if (text.length() == 0) {
            // auto convert to uppercase S
            if (ch == 's' || ch == 'S') {
                txtStudentId.setText("S");
            } else {
                e.consume();
            }
            e.consume();
            return;
        }

        // Remaining characters must be digits
        if (!Character.isDigit(ch)) {
            e.consume();
        }
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStudentId;
    private javax.swing.JTable tableGrades;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
